Repository dnd-side-project/dnd-9th-10-backend, pull requests merged in 2023-08, with the labels that each got.

#9 feat: 친구 도메인 관련 컨트롤러 구현
  src/main/java/com/dnd/bbok/domain/checklist/dto/request/ChecklistInfoRequestDto.java
  src/main/java/com/dnd/bbok/domain/checklist/dto/request/MyChecklistRequestDto.java
  src/main/java/com/dnd/bbok/domain/checklist/dto/response/ChecklistInfoDto.java
  src/main/java/com/dnd/bbok/domain/checklist/dto/response/MyChecklistDto.java
  src/main/java/com/dnd/bbok/domain/friend/controller/FriendMockController.java
  src/main/java/com/dnd/bbok/domain/friend/dto/request/FriendRequestDto.java
  src/main/java/com/dnd/bbok/domain/friend/dto/response/BbokCharacterDto.java
  src/main/java/com/dnd/bbok/domain/friend/dto/response/BbokCharactersDto.java
  src/main/java/com/dnd/bbok/domain/friend/dto/response/FriendDto.java
  src/main/java/com/dnd/bbok/domain/friend/dto/response/FriendsDto.java
  src/main/java/com/dnd/bbok/domain/friend/entity/BbokCharacter.java
Labels: ✨ Feature

#10 feat: 체크리스트 도메인 관련 Mock 컨트롤러 구현
  src/main/java/com/dnd/bbok/domain/checklist/controller/ChecklistMockController.java
  src/main/java/com/dnd/bbok/domain/checklist/dto/request/MemberChecklistRequestDto.java
  src/main/java/com/dnd/bbok/domain/checklist/dto/response/BasicChecklistDto.java
  src/main/java/com/dnd/bbok/domain/friend/controller/FriendMockController.java
Labels: ✨ Feature

#11 feat: 명언,북마크와 관련된 mock 컨트롤러를 구현합니다.
  src/main/java/com/dnd/bbok/domain/saying/controller/SayingMockController.java
  src/main/java/com/dnd/bbok/domain/saying/dto/request/BookmarkRequestDto.java
  src/main/java/com/dnd/bbok/domain/saying/dto/response/BookmarkInfoDto.java
  src/main/java/com/dnd/bbok/domain/saying/dto/response/SayingInfoDto.java
Labels: ✨ Feature

#12 feat: 일기와 관련된 Mock Controller 구현
  src/main/java/com/dnd/bbok/domain/diary/controller/DiaryMockController.java
  src/main/java/com/dnd/bbok/domain/diary/dto/request/DiaryRequestDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiariesDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiaryChecklistDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiaryCreateDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiaryDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiarySayingDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiaryStickerDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiaryTagDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/StickerDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/TagDto.java
Labels: ✨ Feature

#16 setting: SwaggerConfig 변경
  src/main/java/com/dnd/bbok/domain/member/controller/MemberController.java
  src/main/java/com/dnd/bbok/infra/swagger/SwaggerConfig.java
  src/main/java/com/dnd/bbok/mock/ChecklistMockController.java
  src/main/java/com/dnd/bbok/mock/DiaryMockController.java
  src/main/java/com/dnd/bbok/mock/FriendMockController.java
  src/main/java/com/dnd/bbok/mock/SayingMockController.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ⚙️ Setting

#26 feat: 토큰 재발급 Api 구현
  src/main/java/com/dnd/bbok/domain/jwt/controller/JwtController.java
  src/main/java/com/dnd/bbok/domain/jwt/dto/ReIssueTokenDto.java
  src/main/java/com/dnd/bbok/domain/jwt/dto/SessionUser.java
  src/main/java/com/dnd/bbok/domain/jwt/exception/JwtException.java
  src/main/java/com/dnd/bbok/domain/jwt/filter/JwtAuthenticationEntryPointHandler.java
  src/main/java/com/dnd/bbok/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/dnd/bbok/domain/jwt/filter/JwtExceptionFilter.java
  src/main/java/com/dnd/bbok/domain/jwt/service/JwtTokenProvider.java
  src/main/java/com/dnd/bbok/domain/jwt/service/JwtTokenReissueService.java
  src/main/java/com/dnd/bbok/domain/member/controller/MemberController.java
  src/main/java/com/dnd/bbok/domain/member/service/MemberInfoService.java
  src/main/java/com/dnd/bbok/domain/member/service/MemberService.java
  src/main/java/com/dnd/bbok/domain/member/service/MemberSignUpService.java
  src/main/java/com/dnd/bbok/global/exception/ErrorCode.java
  src/main/java/com/dnd/bbok/global/security/SecurityConfig.java
  src/main/java/com/dnd/bbok/global/util/CookieUtil.java
  src/main/java/com/dnd/bbok/infra/redis/RedisService.java
  src/main/java/com/dnd/bbok/infra/redis/RefreshToken.java
  src/main/java/com/dnd/bbok/infra/redis/RefreshTokenRepository.java
  src/main/java/com/dnd/bbok/infra/swagger/SwaggerConfig.java
Labels: ✨ Feature, ⭐️ Refactoring

#27 fix: GitHub action build 실패 오류 해결
  src/main/java/com/dnd/bbok/domain/checklist/controller/ChecklistController.java
  src/main/java/com/dnd/bbok/domain/checklist/service/MemberChecklistUseCaseService.java
Labels: 🐞 Bug, 🛠️ Fix

#28 [Feature/#17]: 뽁 캐릭터 기본 제공 기능 구현
  build.gradle
  src/main/java/com/dnd/bbok/ServerApplication.java
  src/main/java/com/dnd/bbok/domain/friend/controller/FriendController.java
  src/main/java/com/dnd/bbok/domain/friend/dto/response/BbokCharacterDto.java
  src/main/java/com/dnd/bbok/domain/friend/dto/response/BbokCharactersDto.java
  src/main/java/com/dnd/bbok/domain/friend/entity/BbokCharacter.java
  src/main/java/com/dnd/bbok/domain/friend/service/IconService.java
  src/main/java/com/dnd/bbok/global/security/SecurityConfig.java
  src/main/java/com/dnd/bbok/infra/s3/config/S3Config.java
  src/main/java/com/dnd/bbok/infra/s3/service/S3Downloader.java
  src/main/java/com/dnd/bbok/infra/swagger/SwaggerConfig.java
  src/main/java/com/dnd/bbok/mock/FriendMockController.java
  src/main/resources/application-prod.yml
  src/test/resources/application.yml
Labels: ✨ Feature

#31 fix: Cors 에러를 해결합니다.
  src/main/java/com/dnd/bbok/ServerApplication.java
  src/main/java/com/dnd/bbok/domain/member/controller/MemberController.java
Labels: 🛠️ Fix

#32 fix: allowedOrigin 에 서비스 도메인 주소 추가
  src/main/java/com/dnd/bbok/ServerApplication.java
Labels: 🛠️ Fix

#33 feat: 친구 캐릭터 생성 기능 구현
  src/main/java/com/dnd/bbok/domain/friend/controller/FriendController.java
  src/main/java/com/dnd/bbok/domain/friend/dto/request/FriendRequestDto.java
  src/main/java/com/dnd/bbok/domain/friend/entity/Friend.java
  src/main/java/com/dnd/bbok/domain/friend/exception/CharacterNotFoundException.java
  src/main/java/com/dnd/bbok/domain/friend/exception/FriendCreationException.java
  src/main/java/com/dnd/bbok/domain/friend/repository/FriendRepository.java
  src/main/java/com/dnd/bbok/domain/friend/service/FriendService.java
  src/main/java/com/dnd/bbok/domain/friend/service/MemberFriendUseCaseService.java
  src/main/java/com/dnd/bbok/domain/member/dto/response/LoginResponseDto.java
  src/main/java/com/dnd/bbok/domain/member/service/MemberSignUpService.java
  src/main/java/com/dnd/bbok/global/exception/ErrorCode.java
  src/main/java/com/dnd/bbok/global/security/SecurityConfig.java
  src/main/java/com/dnd/bbok/mock/FriendMockController.java
Labels: ✨ Feature

#34 [Feature/#23] 일기 생성기능 구현
  src/main/java/com/dnd/bbok/domain/checklist/entity/DiaryChecklist.java
  src/main/java/com/dnd/bbok/domain/checklist/repository/DiaryChecklistRepository.java
  src/main/java/com/dnd/bbok/domain/checklist/repository/MemberChecklistRepository.java
  src/main/java/com/dnd/bbok/domain/checklist/service/DiaryChecklistEntityService.java
  src/main/java/com/dnd/bbok/domain/checklist/service/DiaryChecklistService.java
  src/main/java/com/dnd/bbok/domain/checklist/service/MemberChecklistEntityService.java
  src/main/java/com/dnd/bbok/domain/checklist/service/MemberChecklistUseCaseService.java
  src/main/java/com/dnd/bbok/domain/diary/controller/DiaryController.java
  src/main/java/com/dnd/bbok/domain/diary/dto/request/ChecklistDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/request/DiaryRequestDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiaryCreateDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiarySayingDto.java
  src/main/java/com/dnd/bbok/domain/diary/entity/Diary.java
  src/main/java/com/dnd/bbok/domain/diary/repository/DiaryRepository.java
  src/main/java/com/dnd/bbok/domain/diary/service/DiaryEntityService.java
  src/main/java/com/dnd/bbok/domain/diary/service/DiaryService.java
  src/main/java/com/dnd/bbok/domain/diary/service/FriendTempService.java
  src/main/java/com/dnd/bbok/domain/friend/entity/Friend.java
  src/main/java/com/dnd/bbok/domain/saying/dto/response/SayingInfoDto.java
  src/main/java/com/dnd/bbok/domain/saying/repository/BookmarkRepository.java
  src/main/java/com/dnd/bbok/domain/saying/repository/SayingRepository.java
  src/main/java/com/dnd/bbok/domain/saying/service/BookmarkEntityService.java
  src/main/java/com/dnd/bbok/domain/saying/service/SayingEntityService.java
  src/main/java/com/dnd/bbok/domain/saying/service/SayingService.java
  src/main/java/com/dnd/bbok/domain/tag/entity/DiaryTag.java
  src/main/java/com/dnd/bbok/domain/tag/entity/FriendTag.java
  src/main/java/com/dnd/bbok/domain/tag/entity/Tag.java
  src/main/java/com/dnd/bbok/domain/tag/repository/DiaryTagRepository.java
  src/main/java/com/dnd/bbok/domain/tag/repository/FriendTagRepository.java
  src/main/java/com/dnd/bbok/domain/tag/service/DiaryTagEntityService.java
  src/main/java/com/dnd/bbok/domain/tag/service/FriendTagEntityService.java
  src/main/java/com/dnd/bbok/domain/tag/service/TagService.java
  src/main/java/com/dnd/bbok/global/exception/ErrorCode.java
  src/main/java/com/dnd/bbok/mock/DiaryMockController.java
  src/main/resources/application-dev.yml
Labels: ✨ Feature

#39 refactor: jwt 관련 서버 에러 정의, CORS allowed origin 추가
  src/main/java/com/dnd/bbok/ServerApplication.java
  src/main/java/com/dnd/bbok/domain/jwt/service/JwtTokenProvider.java
  src/main/java/com/dnd/bbok/global/exception/ErrorCode.java
Labels: ⭐️ Refactoring

#40 [Feature/#23] 일기 조회 / 친구별 태그 조회 api 구현
  src/main/java/com/dnd/bbok/domain/checklist/repository/DiaryChecklistRepository.java
  src/main/java/com/dnd/bbok/domain/checklist/service/DiaryChecklistEntityService.java
  src/main/java/com/dnd/bbok/domain/checklist/service/DiaryChecklistService.java
  src/main/java/com/dnd/bbok/domain/diary/controller/DiaryController.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiaryChecklistDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiaryDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiaryTagDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/TagDto.java
  src/main/java/com/dnd/bbok/domain/diary/repository/DiaryRepository.java
  src/main/java/com/dnd/bbok/domain/diary/service/DiaryEntityService.java
  src/main/java/com/dnd/bbok/domain/diary/service/DiaryService.java
  src/main/java/com/dnd/bbok/domain/saying/service/SayingEntityService.java
  src/main/java/com/dnd/bbok/domain/saying/service/SayingService.java
  src/main/java/com/dnd/bbok/domain/tag/entity/DiaryTag.java
  src/main/java/com/dnd/bbok/domain/tag/repository/DiaryTagRepository.java
  src/main/java/com/dnd/bbok/domain/tag/service/DiaryTagEntityService.java
  src/main/java/com/dnd/bbok/domain/tag/service/TagService.java
  src/main/java/com/dnd/bbok/global/exception/ErrorCode.java
  src/main/java/com/dnd/bbok/mock/DiaryMockController.java
Labels: ✨ Feature

#41 fix: 로그인 관련 불필요한 예외 처리 정리
  src/main/java/com/dnd/bbok/domain/jwt/service/JwtTokenProvider.java
  src/main/java/com/dnd/bbok/domain/member/controller/MemberController.java
  src/main/java/com/dnd/bbok/domain/member/service/MemberSignUpService.java
Labels: ✨ Feature, 🛠️ Fix

#43 feat: 나만의 기준 조회 기능 구현
  src/main/java/com/dnd/bbok/domain/checklist/dto/response/ChecklistInfoDto.java
  src/main/java/com/dnd/bbok/domain/checklist/dto/response/MyChecklistDto.java
  src/main/java/com/dnd/bbok/domain/checklist/repository/MemberChecklistRepository.java
  src/main/java/com/dnd/bbok/domain/checklist/service/MemberChecklistEntityService.java
  src/main/java/com/dnd/bbok/domain/checklist/service/MemberChecklistUseCaseService.java
  src/main/java/com/dnd/bbok/domain/friend/controller/FriendController.java
  src/main/java/com/dnd/bbok/mock/FriendMockController.java
Labels: ✨ Feature

#42 feat: 등록한 친구 목록 조회 기능 구현
  src/main/java/com/dnd/bbok/domain/common/BaseTimeEntity.java
  src/main/java/com/dnd/bbok/domain/diary/repository/DiaryRepository.java
  src/main/java/com/dnd/bbok/domain/diary/service/DiaryEntityService.java
  src/main/java/com/dnd/bbok/domain/diary/service/FriendTempService.java
  src/main/java/com/dnd/bbok/domain/friend/controller/FriendController.java
  src/main/java/com/dnd/bbok/domain/friend/dto/response/FriendDto.java
  src/main/java/com/dnd/bbok/domain/friend/dto/response/FriendsDto.java
  src/main/java/com/dnd/bbok/domain/friend/entity/Friend.java
  src/main/java/com/dnd/bbok/domain/friend/repository/FriendRepository.java
  src/main/java/com/dnd/bbok/domain/friend/service/DiaryFriendUseCaseService.java
  src/main/java/com/dnd/bbok/domain/friend/service/FriendService.java
  src/main/java/com/dnd/bbok/domain/friend/service/IconService.java
  src/main/java/com/dnd/bbok/domain/friend/service/MemberFriendUseCaseService.java
  src/main/java/com/dnd/bbok/global/exception/ErrorCode.java
  src/main/java/com/dnd/bbok/global/security/SecurityConfig.java
  src/main/java/com/dnd/bbok/mock/FriendMockController.java
Labels: ✨ Feature

#44 fix: merge 충돌 해결
  src/main/java/com/dnd/bbok/domain/friend/controller/FriendController.java
  src/main/java/com/dnd/bbok/mock/FriendMockController.java
Labels: 🛠️ Fix

#45 Feature/#19
  src/main/java/com/dnd/bbok/domain/friend/controller/FriendController.java
Labels: 🛠️ Fix

#47 [Refactor/#46] Basic Checklist 조회 Logic 헥사고날 아키텍쳐로 변경
  src/main/java/com/dnd/bbok/basicchecklist/adapter/in/web/BasicChecklistController.java
  src/main/java/com/dnd/bbok/basicchecklist/adapter/out/persistence/BasicChecklistEntity.java
  src/main/java/com/dnd/bbok/basicchecklist/adapter/out/persistence/BasicChecklistMapper.java
  src/main/java/com/dnd/bbok/basicchecklist/adapter/out/persistence/BasicChecklistPersistenceAdapter.java
  src/main/java/com/dnd/bbok/basicchecklist/adapter/out/persistence/BasicChecklistRepository.java
  src/main/java/com/dnd/bbok/basicchecklist/application/port/in/GetBasicChecklistQuery.java
  src/main/java/com/dnd/bbok/basicchecklist/application/port/in/GetBasicChecklistResponse.java
  src/main/java/com/dnd/bbok/basicchecklist/application/port/out/LoadBasicChecklistPort.java
  src/main/java/com/dnd/bbok/basicchecklist/application/service/BasicChecklistService.java
  src/main/java/com/dnd/bbok/basicchecklist/domain/BasicChecklist.java
  src/main/java/com/dnd/bbok/domain/checklist/controller/ChecklistController.java
  src/main/java/com/dnd/bbok/domain/checklist/dto/response/BasicChecklistDto.java
  src/main/java/com/dnd/bbok/domain/checklist/repository/BasicChecklistRepository.java
  src/main/java/com/dnd/bbok/domain/checklist/service/BasicChecklistService.java
  src/main/java/com/dnd/bbok/infra/swagger/SwaggerConfig.java
Labels: ⭐️ Refactoring

#49 refactor: Member 패키지 구조 리팩토링
  src/main/java/com/dnd/bbok/domain/member/controller/MemberController.java
  src/main/java/com/dnd/bbok/domain/member/dto/response/MemberInfoResponseDto.java
  src/main/java/com/dnd/bbok/domain/member/service/MemberInfoService.java
  src/main/java/com/dnd/bbok/infra/swagger/SwaggerConfig.java
  src/main/java/com/dnd/bbok/member/adapter/in/web/GetAllMemberController.java
  src/main/java/com/dnd/bbok/member/adapter/out/persistence/MemberPersistenceAdapter.java
  src/main/java/com/dnd/bbok/member/adapter/out/persistence/entity/MemberEntity.java
  src/main/java/com/dnd/bbok/member/adapter/out/persistence/mapper/MemberMapper.java
  src/main/java/com/dnd/bbok/member/adapter/out/persistence/repository/MemberTestRepository.java
  src/main/java/com/dnd/bbok/member/application/port/in/GetMemberInfoResponse.java
  src/main/java/com/dnd/bbok/member/application/port/in/GetMemberQuery.java
  src/main/java/com/dnd/bbok/member/application/port/out/LoadMemberPort.java
  src/main/java/com/dnd/bbok/member/application/service/MemberTestService.java
  src/main/java/com/dnd/bbok/member/domain/Member.java
  src/main/java/com/dnd/bbok/member/domain/OAuth2Provider.java
  src/main/java/com/dnd/bbok/member/domain/Role.java
Labels: ⭐️ Refactoring

#55 chore: 친구 관련 패키지 구조 틀 생성
  src/main/java/com/dnd/bbok/domain/friend/controller/FriendController.java
  src/main/java/com/dnd/bbok/friend/adapter/in/web/GetFriendCharacterController.java
  src/main/java/com/dnd/bbok/friend/adapter/out/persistence/entity/FriendEntity.java
  src/main/java/com/dnd/bbok/friend/adapter/out/persistence/repository/FriendTestRepository.java
  src/main/java/com/dnd/bbok/friend/application/port/in/usecase/GetIconQuery.java
  src/main/java/com/dnd/bbok/friend/application/port/out/LoadIconPort.java
  src/main/java/com/dnd/bbok/friend/application/service/FriendIconService.java
  src/main/java/com/dnd/bbok/friend/domain/BbokCharacter.java
  src/main/java/com/dnd/bbok/friend/domain/Friend.java
Labels: ⭐️ Refactoring

#63 feat: 친구 도메인 관련 기능 구현
  src/main/java/com/dnd/bbok/common/BaseTimeEntity.java
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/entity/DiaryEntity.java
  src/main/java/com/dnd/bbok/diary/application/service/CreateDiaryService.java
  src/main/java/com/dnd/bbok/domain/friend/entity/Friend.java
  src/main/java/com/dnd/bbok/domain/member/entity/Member.java
  src/main/java/com/dnd/bbok/friend/adapter/in/web/EditFriendInfoController.java
  src/main/java/com/dnd/bbok/friend/adapter/in/web/GetFriendCharacterController.java
  src/main/java/com/dnd/bbok/friend/adapter/in/web/GetFriendsController.java
  src/main/java/com/dnd/bbok/friend/adapter/in/web/RegisterFriendController.java
  src/main/java/com/dnd/bbok/friend/adapter/out/persistence/FriendPersistenceAdapter.java
  src/main/java/com/dnd/bbok/friend/adapter/out/persistence/entity/FriendEntity.java
  src/main/java/com/dnd/bbok/friend/adapter/out/persistence/mapper/FriendMapper.java
  src/main/java/com/dnd/bbok/friend/adapter/out/persistence/repository/FriendTestRepository.java
  src/main/java/com/dnd/bbok/friend/application/port/in/request/FriendInfoRequest.java
  src/main/java/com/dnd/bbok/friend/application/port/in/request/UpdateFriendRequest.java
  src/main/java/com/dnd/bbok/friend/application/port/in/response/BbokCharacterGroupInfo.java
  src/main/java/com/dnd/bbok/friend/application/port/in/response/BbokCharacterInfo.java
  src/main/java/com/dnd/bbok/friend/application/port/in/response/FriendGroupInfo.java
  src/main/java/com/dnd/bbok/friend/application/port/in/response/FriendInfo.java
  src/main/java/com/dnd/bbok/friend/application/port/in/usecase/EditFriendUseCase.java
  src/main/java/com/dnd/bbok/friend/application/port/in/usecase/GetFriendsQuery.java
  src/main/java/com/dnd/bbok/friend/application/port/in/usecase/GetIconQuery.java
  src/main/java/com/dnd/bbok/friend/application/port/in/usecase/RegisterFriendUseCase.java
  src/main/java/com/dnd/bbok/friend/application/port/out/FriendValidatorPort.java
  src/main/java/com/dnd/bbok/friend/application/port/out/SaveFriendPort.java
  src/main/java/com/dnd/bbok/friend/application/port/out/UpdateFriendPort.java
  src/main/java/com/dnd/bbok/friend/application/service/FriendIconService.java
  src/main/java/com/dnd/bbok/friend/application/service/FriendTestService.java
  src/main/java/com/dnd/bbok/friend/domain/Friend.java
  src/main/java/com/dnd/bbok/global/exception/ErrorCode.java
  src/main/java/com/dnd/bbok/global/security/SecurityConfig.java
  src/main/java/com/dnd/bbok/member/adapter/in/web/EditMemberChecklistController.java
  src/main/java/com/dnd/bbok/member/adapter/out/persistence/MemberPersistenceAdapter.java
  src/main/java/com/dnd/bbok/member/adapter/out/persistence/entity/MemberChecklistEntity.java
  src/main/java/com/dnd/bbok/member/adapter/out/persistence/entity/MemberEntity.java
  src/main/java/com/dnd/bbok/member/application/port/in/request/ChecklistInfoRequest.java
  src/main/java/com/dnd/bbok/member/application/port/in/request/EditMemberChecklistRequest.java
  src/main/java/com/dnd/bbok/member/application/port/in/usecase/EditMemberChecklistUseCase.java
  src/main/java/com/dnd/bbok/member/application/port/out/EditMemberChecklistPort.java
  src/main/java/com/dnd/bbok/member/application/service/MemberTestService.java
  src/main/java/com/dnd/bbok/saying/adapter/out/persistence/entity/SayingEntity.java
Labels: ✨ Feature

#64 refactor: 일기 목록 조회기능 및 태그 조회기능 리팩토링, 일기 조회기능 구현
  src/main/java/com/dnd/bbok/basicchecklist/adapter/in/web/BasicChecklistController.java
  src/main/java/com/dnd/bbok/diary/adapter/in/web/CreateDiaryController.java
  src/main/java/com/dnd/bbok/diary/adapter/in/web/GetDiariesController.java
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/DiaryAdapter.java
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/mapper/DiaryChecklistMapper.java
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/mapper/DiaryMapper.java
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/mapper/DiaryTagMapper.java
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/repository/DiaryChecklistRepository.java
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/repository/DiaryTagRepository.java
  src/main/java/com/dnd/bbok/diary/application/port/in/response/GetDiariesResponse.java
  src/main/java/com/dnd/bbok/diary/application/port/in/response/GetDiaryResponse.java
  src/main/java/com/dnd/bbok/diary/application/port/in/usecase/GetDiariesQuery.java
  src/main/java/com/dnd/bbok/diary/application/port/in/usecase/GetDiaryQuery.java
  src/main/java/com/dnd/bbok/diary/application/port/out/LoadDiaryPort.java
  src/main/java/com/dnd/bbok/diary/application/port/out/SaveDiaryPort.java
  src/main/java/com/dnd/bbok/diary/application/service/CreateDiaryService.java
  src/main/java/com/dnd/bbok/diary/application/service/GetDiaryService.java
  src/main/java/com/dnd/bbok/diary/domain/DiaryChecklist.java
  src/main/java/com/dnd/bbok/diary/domain/Tag.java
  src/main/java/com/dnd/bbok/domain/checklist/dto/request/MyChecklistRequestDto.java
  src/main/java/com/dnd/bbok/domain/checklist/service/DiaryChecklistEntityService.java
  src/main/java/com/dnd/bbok/domain/checklist/service/DiaryChecklistService.java
  src/main/java/com/dnd/bbok/domain/checklist/service/MemberChecklistEntityService.java
  src/main/java/com/dnd/bbok/domain/diary/controller/DiaryController.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiaryChecklistDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiaryTagDto.java
  src/main/java/com/dnd/bbok/domain/diary/service/DiaryService.java
  src/main/java/com/dnd/bbok/domain/diary/service/FriendTempService.java
  src/main/java/com/dnd/bbok/friend/adapter/in/web/GetFriendTagsController.java
  src/main/java/com/dnd/bbok/friend/application/port/in/response/GetFriendTagsResponse.java
  src/main/java/com/dnd/bbok/friend/application/port/in/usecase/GetFriendTagsQuery.java
  src/main/java/com/dnd/bbok/friend/application/service/GetFriendTagsService.java
  src/main/java/com/dnd/bbok/global/exception/ErrorCode.java
  src/main/java/com/dnd/bbok/mock/DiaryMockController.java
Labels: ⭐️ Refactoring

#76 [refactor/#75]: Domain 루트 패키지 제거 및 내부 클래스들 각자 헥사고날 아키텍처에 맞는 위치로 이동, 기존 서비스 …
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/DiaryAdapter.java
  src/main/java/com/dnd/bbok/diary/application/port/in/response/CreateDiaryResponse.java
  src/main/java/com/dnd/bbok/diary/application/port/in/response/DiarySaying.java
  src/main/java/com/dnd/bbok/diary/application/port/in/response/GetDiaryStickerResponse.java
  src/main/java/com/dnd/bbok/diary/application/port/out/LoadDiaryPort.java
  src/main/java/com/dnd/bbok/diary/application/service/CreateDiaryService.java
  src/main/java/com/dnd/bbok/diary/domain/DiarySaying.java
  src/main/java/com/dnd/bbok/domain/checklist/dto/request/ChecklistInfoRequestDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/DiaryStickerDto.java
  src/main/java/com/dnd/bbok/domain/diary/dto/response/StickerDto.java
  src/main/java/com/dnd/bbok/domain/diary/service/DiaryEntityService.java
  src/main/java/com/dnd/bbok/domain/saying/dto/response/BookmarkInfoDto.java
  src/main/java/com/dnd/bbok/domain/saying/dto/response/SayingInfoDto.java
  src/main/java/com/dnd/bbok/domain/tag/service/DiaryTagEntityService.java
  src/main/java/com/dnd/bbok/domain/tag/service/FriendTagEntityService.java
  src/main/java/com/dnd/bbok/domain/tag/service/TagService.java
  src/main/java/com/dnd/bbok/friend/application/service/FriendService.java
  src/main/java/com/dnd/bbok/mock/DiaryMockController.java
  src/main/java/com/dnd/bbok/mock/FriendMockController.java
Labels: ⭐️ Refactoring

#77 [Feature/#72] 일기 목록 페이징 및 검색 / 정렬기능 구현
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/DiaryAdapter.java
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/entity/DiaryEntity.java
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/mapper/DiaryMapper.java
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/repository/DiaryRepository.java
  src/main/java/com/dnd/bbok/diary/application/port/in/response/GetDiariesResponse.java
  src/main/java/com/dnd/bbok/diary/application/port/out/LoadDiaryPort.java
  src/main/java/com/dnd/bbok/diary/application/service/GetDiaryService.java
Labels: ✨ Feature

#81 refactor: 코드리뷰 피드백 적용
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/DiaryAdapter.java
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/repository/DiaryRepository.java
  src/main/java/com/dnd/bbok/diary/domain/Diary.java
Labels: ⭐️ Refactoring

#82 Feature/#69
  src/main/java/com/dnd/bbok/diary/adapter/in/web/GetStickerController.java
  src/main/java/com/dnd/bbok/diary/adapter/out/persistence/DiaryAdapter.java
  src/main/java/com/dnd/bbok/diary/application/port/in/response/GetDiaryStickerResponse.java
  src/main/java/com/dnd/bbok/diary/application/port/in/usecase/GetStickerQuery.java
  src/main/java/com/dnd/bbok/diary/application/service/GetStickerService.java
  src/main/java/com/dnd/bbok/diary/application/service/WriteDiaryService.java
  src/main/java/com/dnd/bbok/diary/domain/Sticker.java
  src/main/java/com/dnd/bbok/mock/DiaryMockController.java
Labels: ✨ Feature

#83 feat: 기준 수정사항 기능 구현
  src/main/java/com/dnd/bbok/diary/application/service/WriteDiaryService.java
  src/main/java/com/dnd/bbok/friend/adapter/out/persistence/FriendCharacterAdapter.java
  src/main/java/com/dnd/bbok/friend/adapter/out/persistence/FriendPersistenceAdapter.java
  src/main/java/com/dnd/bbok/friend/adapter/out/persistence/mapper/FriendMapper.java
  src/main/java/com/dnd/bbok/friend/adapter/out/persistence/repository/FriendRepository.java
  src/main/java/com/dnd/bbok/friend/application/port/out/FriendValidatorPort.java
  src/main/java/com/dnd/bbok/friend/application/port/out/LoadFriendPort.java
  src/main/java/com/dnd/bbok/friend/application/port/out/LoadIconPort.java
  src/main/java/com/dnd/bbok/friend/application/port/out/SaveFriendPort.java
  src/main/java/com/dnd/bbok/friend/application/port/out/UpdateFriendPort.java
  src/main/java/com/dnd/bbok/friend/application/service/FriendService.java
  src/main/java/com/dnd/bbok/friend/domain/Friend.java
  src/main/java/com/dnd/bbok/global/exception/ErrorCode.java
  src/main/java/com/dnd/bbok/global/security/SecurityConfig.java
  src/main/java/com/dnd/bbok/infra/swagger/SwaggerConfig.java
  src/main/java/com/dnd/bbok/member/adapter/in/web/EditMemberChecklistController.java
  src/main/java/com/dnd/bbok/member/adapter/in/web/GetMemberChecklistController.java
  src/main/java/com/dnd/bbok/member/adapter/out/persistence/MemberPersistenceAdapter.java
  src/main/java/com/dnd/bbok/member/adapter/out/persistence/entity/MemberChecklistEntity.java
  src/main/java/com/dnd/bbok/member/adapter/out/persistence/mapper/MemberChecklistMapper.java
  src/main/java/com/dnd/bbok/member/adapter/out/persistence/mapper/MemberMapper.java
  src/main/java/com/dnd/bbok/member/application/port/in/request/EditMemberChecklistRequest.java
  src/main/java/com/dnd/bbok/member/application/port/in/response/GetDetailMemberChecklistResponse.java
  src/main/java/com/dnd/bbok/member/application/port/in/response/GetMemberChecklistResponse.java
  src/main/java/com/dnd/bbok/member/application/port/out/EditMemberChecklistPort.java
  src/main/java/com/dnd/bbok/member/application/port/out/LoadMemberChecklistPort.java
  src/main/java/com/dnd/bbok/member/application/port/out/SaveMemberChecklistPort.java
  src/main/java/com/dnd/bbok/member/application/service/MemberService.java
  src/main/java/com/dnd/bbok/member/domain/ChecklistInfo.java
  src/main/java/com/dnd/bbok/member/domain/MemberChecklist.java
  src/main/java/com/dnd/bbok/mock/FriendMockController.java
  src/main/java/com/dnd/bbok/saying/adapter/out/persistence/BookmarkAdapter.java
  src/main/java/com/dnd/bbok/saying/adapter/out/persistence/mapper/SayingMapper.java
Labels: ✨ Feature
